Run coverage report on success or failure (not canceled)

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -45,8 +45,10 @@ jobs:
         run: poetry install --no-interaction --no-root
 
       - name: 🏗️ Install dependencies
+        run: poetry install --no-interaction
+
+      - name: 🛸 Configure extra test dependencies
         run: |
-          poetry install --no-interaction
           sudo apt install -y libfuse2 fonts-open-sans
           mkdir -p data
 
@@ -55,9 +57,11 @@ jobs:
 
       - name: 🧪 Run pytest suite
         run: poetry run pytest -v --cov --cov-report lcov ${{ inputs.pytest_args }}
-        continue-on-error: true
 
       - name: 📈 Uploade coverage report
+        # always run this step, even if the tests fail
+        # putting always() would cause the function to run even if the build is canceled
+        if: success() || failure()
         uses: codecov/codecov-action@v3
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
